### ISSUE TITLE
On the status of Vicare Scheme support and failing tests

### ISSUE THREAD

**Issue by marcomaggi** [weinholt/industria#1]
In my fork of Industria, `vicare-scheme` branch, I am working on Vicare Scheme support.  After fixing compatibility libraries and errors in Vicare (but notice Vicare [issue #49](https://github.com/marcomaggi/vicare/issues/49)) I am down to one problem: the test file `x86asm.sps` fails with:

```
*** Vicare: unhandled exception:
 Condition components:
   1. &error
   2. &who: encode-memory
   3. &message: "Displacement can't be encoded"
   4. &irritants: (18374966859431673855)
```

on my `x86_64-unknown-linux-gnu`; the relevant source code is tagged with a FIXME comment, so is this test supposed to fail when using Industria commit 7425df6c4e6dc8ba154dc0e98d837d8ca062a1fc?

**Comment by weinholt** [comment]
Code was moved to https://github.com/weinholt/machine-code
