### ISSUE TITLE
Replacement for Ed25519 signing and X25519 key exchange?

### ISSUE THREAD

**Issue by amirouche** [weinholt/industria#8]
Apparently, Ed25519 signing and X25519 key exchange are state of the art.

How can create those using industria?

**Comment by weinholt** [comment]
There is currently no support for these algorithms in Industria.

Industria is lagging behind the state of the art.

**Comment by amirouche** [comment]
What do you recommend to use instead?

**Comment by weinholt** [comment]
I haven't looked at Ed25519 yet and can't recommend anything.

**Comment by weinholt** [comment]
Left to do:

- [ ] X25519 algorithm
- [ ] SSH: Signing/verifying with Ed25519 & add to algorithms.sls
- [ ] X.509 support for Ed25519
- [ ] Documentation
